source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BUKCollectionFlowView_Example', :exclusive => true do
  pod "BUKCollectionFlowView", :path => "../"
end

target 'BUKCollectionFlowView_Tests', :exclusive => true do
  pod "BUKCollectionFlowView", :path => "../"

end
